// Copyright (c) 2013 PlintaGroup.
// All rights reserved.
// This file is for Object C targets
// The file is auto generated, please do not change

#ifndef Volvo_Remote_mqtt_strings_h
#define Volvo_Remote_mqtt_strings_h

// Volume for media setting and getting volume payload (0..100) in %
#define mediaVolumeCommandAvailable                        @"commandavailable/mediaservice/volume"
#define mediaVolumeCommand                                 @"command/mediaservice/volume"
#define mediaVolumeDataAvailable                           @"dataavailable/mediaservice/volume"
#define mediaVolumeData                                    @"data/mediaservice/volume"
// Mute the the volume. Payload (true/false)
#define mediaMuteCommandAvailable                          @"commandavailable/mediaservice/mute"
#define mediaMuteCommand                                   @"command/mediaservice/mute"
#define mediaMuteDataAvailable                             @"dataavailable/mediaservice/mute"
#define mediaMuteData                                      @"data/mediaservice/mute"
// mix setting and getting Mix state Mix is a true false Payload (true/false)
#define mediaMixCommandAvailable                           @"commandavailable/mediaservice/mix"
#define mediaMixCommand                                    @"command/mediaservice/mix"
#define mediaMixDataAvailable                              @"dataavailable/mediaservice/mix"
#define mediaMixData                                       @"data/mediaservice/mix"
//  Repeat setting and getting repeat Repeat is a 3 state (offallone) Payload (off/on/one)
#define mediaRepeatCommandAvailable                        @"commandavailable/mediaservice/repeat"
#define mediaRepeatCommand                                 @"command/mediaservice/repeat"
#define mediaRepeatDataAvailable                           @"dataavailable/mediaservice/repeat"
#define mediaRepeatData                                    @"data/mediaservice/repeat"
// Play settings only Play has no payload only a command#
#define mediaPlayCommandAvailable                          @"commandavailable/mediaservice/play"
#define mediaPlayCommand                                   @"command/mediaservice/play"
// Next settings only Next has no payload only a command#
#define mediaNextCommandAvailable                          @"commandavailable/mediaservice/next"
#define mediaNextCommand                                   @"command/mediaservice/next"
// Prev settings only Prev has no payload only a command#
#define mediaPrevCommandAvailable                          @"commandavailable/mediaservice/prev"
#define mediaPrevCommand                                   @"command/mediaservice/prev"
// Payload is seek position in ms
#define mediaSeekCommandAvailable                          @"commandavailable/mediaservice/seek"
#define mediaSeekCommand                                   @"command/mediaservice/seek"
// MediaForUID setting and getting data for a UID as a command request in a JSON list with UID's as data from service JSON with metadata for requested UID (WE NEED TO LOOK AT THIS) #
#define mediaForUIDCommandAvailable                        @"commandavailable/mediaservice/mediaForUID"
#define mediaForUIDCommand                                 @"command/mediaservice/mediaForUID"
#define mediaForUIDDataAvailable                           @"dataavailable/mediaservice/mediaForUID"
#define mediaForUIDData                                    @"data/mediaservice/mediaForUID"
// Position for track both command and data. Payload integer in ms
#define mediaPositionCommandAvailable                      @"commandavailable/mediaservice/position"
#define mediaPositionCommand                               @"command/mediaservice/position"
#define mediaPositionDataAvailable                         @"dataavailable/mediaservice/position"
#define mediaPositionData                                  @"data/mediaservice/position"
// Sources \nsetting and getting setting a source payload (ID for source) Getting a list of sources payload(JSON list of sources with ID)
#define mediaSourceCommandAvailable                        @"commandavailable/mediaservice/source"
#define mediaSourceCommand                                 @"command/mediaservice/source"
#define mediaSourceDataAvailable                           @"dataavailable/mediaservice/source"
#define mediaSourceData                                    @"data/mediaservice/source"
#define mediaTitleDataAvailable                            @"dataavailable/mediaservice/title"
#define mediaTitleData                                     @"data/mediaservice/title"
#define mediaArtistDataAvailable                           @"dataavailable/mediaservice/artist"
#define mediaArtistData                                    @"data/mediaservice/artist"
#define mediaAlbumDataAvailable                            @"dataavailable/mediaservice/album"
#define mediaAlbumData                                     @"data/mediaservice/album"
// Albumart as a base64 encoded png directly in the payload
#define mediaAlbumArtDataAvailable                         @"dataavailable/mediaservice/albumart"
#define mediaAlbumArtData                                  @"data/mediaservice/albumart"
// Song length payload in ms
#define mediaLengthDataAvailable                           @"dataavailable/mediaservice/length"
#define mediaLengthData                                    @"data/mediaservice/length"
#define mediaBufferingDataAvailable                        @"dataavailable/mediaservice/buffering"
#define mediaBufferingData                                 @"data/mediaservice/buffering"
// This is a example of the metadata sent in the playload{"album": "Meddle" "nominal-bitrate": "320000" "track-number": "5" "has-crc": "False" "artist": "Pink Floyd" "title": "Seamus" "genre": "Progressive Rock" "date": "<GstDate: 1/1/1971>" "channel-mode": "joint-stereo" "audio-codec": "MPEG 1 Audio Layer 3 (MP3)" "container-format": "ID3 tag"}
#define mediaMetadataDataAvailable                         @"dataavailable/mediaservice/metadata"
#define mediaMetadataData                                  @"data/mediaservice/metadata"
#define mediaStateDataAvailable                            @"dataavailable/mediaservice/mediaState"
#define mediaStateData                                     @"data/mediaservice/mediaState"
#define mediaConnectionDataAvailable                       @"dataavailable/mediaservice/connection"
#define mediaConnectionData                                @"data/mediaservice/connection"
#define mediaPlayUrlsCommandAvailable                      @"commandavailable/mediaservice/playUrls"
#define mediaPlayUrlsCommand                               @"command/mediaservice/playUrls"
#define mediaPlayPauseCommandAvailable                     @"commandavailable/mediaservice/playPause"
#define mediaPlayPauseCommand                              @"command/mediaservice/playPause"
#define mediaPlayPauseDataAvailable                        @"dataavailable/mediaservice/playPause"
#define mediaPlayPauseData                                 @"data/mediaservice/playPause"
// Play a song in the media players internal library list using the songs unique id.
#define mediaPlayIdCommandAvailable                        @"commandavailable/mediaservice/playIndex"
#define mediaPlayIdCommand                                 @"command/mediaservice/playIndex"
#define mediaPlaylistDataAvailable                         @"dataavailable/mediaservice/medialist"
#define mediaPlaylistData                                  @"data/mediaservice/medialist"
#define mediaLibraryListDataAvailable                      @"dataavailable/mediaservice/medialibrarylist"
#define mediaLibraryListData                               @"data/mediaservice/medialibrarylist"
// Temperature for climate service payload (0..40)
#define climaRearAirTemperatureCommandAvailable            @"commandavailable/climateservice/RearAirTemp"
#define climaRearAirTemperatureCommand                     @"command/climateservice/RearAirTemp"
#define climaRearAirTemperatureDataAvailable               @"dataavailable/climateservice/RearAirTemp"
#define climaRearAirTemperatureData                        @"data/climateservice/RearAirTemp"
// Temperature for climate service payload (0..40)
#define climaRearSeatLeftTemperatureCommandAvailable       @"commandavailable/climateservice/RearSeatLeftTemp"
#define climaRearSeatLeftTemperatureCommand                @"command/climateservice/RearSeatLeftTemp"
#define climaRearSeatLeftTemperatureDataAvailable          @"dataavailable/climateservice/RearSeatLeftTemp"
#define climaRearSeatLeftTemperatureData                   @"data/climateservice/RearSeatLeftTemp"
// Temperature for climate service payload (0..40)
#define climaRearSeatRightTemperatureCommandAvailable      @"commandavailable/climateservice/RearSeatRightTemp"
#define climaRearSeatRightTemperatureCommand               @"command/climateservice/RearSeatRightTemp"
#define climaRearSeatRightTemperatureDataAvailable         @"dataavailable/climateservice/RearSeatRightTemp"
#define climaRearSeatRightTemperatureData                  @"data/climateservice/RearSeatRightTemp"
// Fan speed for climate service payload (0..5)
#define climaRearFanSpeedCommandAvailable                  @"commandavailable/climateservice/RearFanSpeed"
#define climaRearFanSpeedCommand                           @"command/climateservice/RearFanSpeed"
#define climaRearFanSpeedDataAvailable                     @"dataavailable/climateservice/RearFanSpeed"
#define climaRearFanSpeedData                              @"data/climateservice/RearFanSpeed"
// Payload for toggling heating function (0..3)
#define climaFrontSeatLeftHeatCommandAvailable             @"commandavailable/climateservice/SeatHeatFrontLevelL"
#define climaFrontSeatLeftHeatCommand                      @"command/climateservice/SeatHeatFrontLevelL"
#define climaFrontSeatLeftHeatDataAvailable                @"dataavailable/climateservice/SeatHeatFrontLevelL"
#define climaFrontSeatLeftHeatData                         @"data/climateservice/SeatHeatFrontLevelL"
// Payload for toggling heating function (0..3)
#define climaFrontSeatRightHeatCommandAvailable            @"commandavailable/climateservice/SeatHeatFrontLevelR"
#define climaFrontSeatRightHeatCommand                     @"command/climateservice/SeatHeatFrontLevelR"
#define climaFrontSeatRightHeatDataAvailable               @"dataavailable/climateservice/SeatHeatFrontLevelR"
#define climaFrontSeatRightHeatData                        @"data/climateservice/SeatHeatFrontLevelR"
// Temperature for climate service payload (0..40)
#define climaFrontLeftAirTempCommandAvailable              @"commandavailable/climateservice/TempLeftDisp"
#define climaFrontLeftAirTempCommand                       @"command/climateservice/TempLeftDisp"
#define climaFrontLeftAirTempDataAvailable                 @"dataavailable/climateservice/TempLeftDisp"
#define climaFrontLeftAirTempData                          @"data/climateservice/TempLeftDisp"
// Temperature for climate service payload (0..40)
#define climaFrontRightAirTempCommandAvailable             @"commandavailable/climateservice/TempRightDisp"
#define climaFrontRightAirTempCommand                      @"command/climateservice/TempRightDisp"
#define climaFrontRightAirTempDataAvailable                @"dataavailable/climateservice/TempRightDisp"
#define climaFrontRightAirTempData                         @"data/climateservice/TempRightDisp"
// Fan speed for climate service payload (0..5)
#define climaFrontFanSpeedCommandAvailable                 @"commandavailable/climateservice/FrontFanSpeed"
#define climaFrontFanSpeedCommand                          @"command/climateservice/FrontFanSpeed"
#define climaFrontFanSpeedDataAvailable                    @"dataavailable/climateservice/FrontFanSpeed"
#define climaFrontFanSpeedData                             @"data/climateservice/FrontFanSpeed"
// Fan speed for climate service payload (0..5)
#define climaManFanDispCommandAvailable                    @"commandavailable/climateservice/ManFanDisp"
#define climaManFanDispCommand                             @"command/climateservice/ManFanDisp"
#define climaManFanDispDataAvailable                       @"dataavailable/climateservice/ManFanDisp"
#define climaManFanDispData                                @"data/climateservice/ManFanDisp"
// Fan speed for climate service payload (0..5)
#define climaFrontSeatLeftFanCommandAvailable              @"commandavailable/climateservice/FrontSeatLeftFan"
#define climaFrontSeatLeftFanCommand                       @"command/climateservice/FrontSeatLeftFan"
#define climaFrontSeatLeftFanDataAvailable                 @"dataavailable/climateservice/FrontSeatLeftFan"
#define climaFrontSeatLeftFanData                          @"data/climateservice/FrontSeatLeftFan"
// Fan speed for climate service payload (0..5)
#define climaFrontSeatRightFanCommandAvailable             @"commandavailable/climateservice/FrontSeatRightFan"
#define climaFrontSeatRightFanCommand                      @"command/climateservice/FrontSeatRightFan"
#define climaFrontSeatRightFanDataAvailable                @"dataavailable/climateservice/FrontSeatRightFan"
#define climaFrontSeatRightFanData                         @"data/climateservice/FrontSeatRightFan"
// Payload for toggling auto function (0/1)
#define climaAutoCommandAvailable                          @"commandavailable/climateservice/Auto"
#define climaAutoCommand                                   @"command/climateservice/Auto"
#define climaAutoDataAvailable                             @"dataavailable/climateservice/Auto"
#define climaAutoData                                      @"data/climateservice/Auto"
// Payload for toggling top function (0/1)
#define climaTopCommandAvailable                           @"commandavailable/climateservice/Top"
#define climaTopCommand                                    @"command/climateservice/Top"
#define climaTopDataAvailable                              @"dataavailable/climateservice/Top"
#define climaTopData                                       @"data/climateservice/Top"
// Payload for toggling middle function (0/1)
#define climaMiddleCommandAvailable                        @"commandavailable/climateservice/Middle"
#define climaMiddleCommand                                 @"command/climateservice/Middle"
#define climaMiddleDataAvailable                           @"dataavailable/climateservice/Middle"
#define climaMiddleData                                    @"data/climateservice/Middle"
// Payload for toggling bottom function (0/1)
#define climaBottomCommandAvailable                        @"commandavailable/climateservice/Bottom"
#define climaBottomCommand                                 @"command/climateservice/Bottom"
#define climaBottomDataAvailable                           @"dataavailable/climateservice/Bottom"
#define climaBottomData                                    @"data/climateservice/Bottom"
// Payload for toggling heating function (0/1)
#define climaSteeringwheelHeatCommandAvailable             @"commandavailable/climateservice/SteeringwheelHeat"
#define climaSteeringwheelHeatCommand                      @"command/climateservice/SteeringwheelHeat"
#define climaSteeringwheelHeatDataAvailable                @"dataavailable/climateservice/SteeringwheelHeat"
#define climaSteeringwheelHeatData                         @"data/climateservice/SteeringwheelHeat"
// Payload for toggling recirculation function (0/1)
#define climaACRecirculateAirCommandAvailable              @"commandavailable/climateservice/ACRecirculateAir"
#define climaACRecirculateAirCommand                       @"command/climateservice/ACRecirculateAir"
#define climaACRecirculateAirDataAvailable                 @"dataavailable/climateservice/ACRecirculateAir"
#define climaACRecirculateAirData                          @"data/climateservice/ACRecirculateAir"
//  Payload: 1 "On" 0 "Off"
#define climaFrontDefrostCommandAvailable                  @"commandavailable/climateservice/FrontDefrosterStatus"
#define climaFrontDefrostCommand                           @"command/climateservice/FrontDefrosterStatus"
#define climaFrontDefrostDataAvailable                     @"dataavailable/climateservice/FrontDefrosterStatus"
#define climaFrontDefrostData                              @"data/climateservice/FrontDefrosterStatus"
//  Payload: 3 "Rear Screen defroster: On Rear View Mirrors Defroster: On" 2 "Rear Screen defroster: Off Rear View Mirrors Defroster: On" 1 "Rear Screen defroster: On Rear View Mirrors Defroster: Off" 0 "Rear Screen defroster: Off Rear View Mirrors Defroster: Off"
#define climaRearDefrostCommandAvailable                   @"commandavailable/climateservice/RearDefrosterStatus"
#define climaRearDefrostCommand                            @"command/climateservice/RearDefrosterStatus"
#define climaRearDefrostDataAvailable                      @"dataavailable/climateservice/RearDefrosterStatus"
#define climaRearDefrostData                               @"data/climateservice/RearDefrosterStatus"
// 6 "OFF - no AC request" 5 "Battery cooling active" 4 "Reduced capacity/power limitation" 7 "OFF - compressor broken" 3 "OFF - Other ECM decision" 2 "OFF - too low pressure on low pressure side - freeze protection" 1 "OFF - too low air temperature after evaporator - normal cycling" 0 "Running"
#define climaACCommandAvailable                            @"commandavailable/climateservice/ACCompressorStatusEVDC"
#define climaACCommand                                     @"command/climateservice/ACCompressorStatusEVDC"
#define climaACDataAvailable                               @"dataavailable/climateservice/ACCompressorStatusEVDC"
#define climaACData                                        @"data/climateservice/ACCompressorStatusEVDC"
#define climaFrontCommandAvailable                         @"commandavailable/climateservice/Front"
#define climaFrontCommand                                  @"command/climateservice/Front"
#define climaFrontDataAvailable                            @"dataavailable/climateservice/Front"
#define climaFrontData                                     @"data/climateservice/Front"
#define climaRearCommandAvailable                          @"commandavailable/climateservice/Rear"
#define climaRearCommand                                   @"command/climateservice/Rear"
#define climaRearDataAvailable                             @"dataavailable/climateservice/Rear"
#define climaRearData                                      @"data/climateservice/Rear"
#define climaDefrostCommandAvailable                       @"commandavailable/climateservice/Defrost"
#define climaDefrostCommand                                @"command/climateservice/Defrost"
#define climaDefrostDataAvailable                          @"dataavailable/climateservice/Defrost"
#define climaDefrostData                                   @"data/climateservice/Defrost"
#define navigationETADataAvailable                         @"dataavailable/navigationservice/eta"
#define navigationETAData                                  @"data/navigationservice/eta"
#define navigationTAADataAvailable                         @"dataavailable/navigationservice/taa"
#define navigationTAAData                                  @"data/navigationservice/taa"
#define navigationNextTurnDataAvailable                    @"dataavailable/navigationservice/nextturn"
#define navigationNextTurnData                             @"data/navigationservice/nextturn"
#define navigationSpeedDataAvailable                       @"dataavailable/navigationservice/speed"
#define navigationSpeedData                                @"data/navigationservice/speed"
#define navigationDrivingAtDataAvailable                   @"dataavailable/navigationservice/drivingat"
#define navigationDrivingAtData                            @"data/navigationservice/drivingat"
#define navigationStartCommandAvailable                    @"commandavailable/navigationservice/location"
#define navigationStartCommand                             @"command/navigationservice/location"
#define navigationStartDataAvailable                       @"dataavailable/navigationservice/location"
#define navigationStartData                                @"data/navigationservice/location"
#define carVariantsDataAvailable                           @"dataavailable/dummycarservice/car"
#define carVariantsData                                    @"data/dummycarservice/car"
#define carinfoFuelLeftDataAvailable                       @"dataavailable/carinfoservice/FuelLevelIndicated"
#define carinfoFuelLeftData                                @"data/carinfoservice/FuelLevelIndicated"
#define carinfoSpeedDataAvailable                          @"dataavailable/carinfoservice/VehicleSpeed"
#define carinfoSpeedData                                   @"data/carinfoservice/VehicleSpeed"
#define carinfoRPMDataAvailable                            @"dataavailable/carinfoservice/EngineSpeed"
#define carinfoRPMData                                     @"data/carinfoservice/EngineSpeed"
#define carinfoENGLoadDataAvailable                        @"dataavailable/carinfoservice/EngineState"
#define carinfoENGLoadData                                 @"data/carinfoservice/EngineState"
#define carinfoOilTempDataAvailable                        @"dataavailable/carinfoservice/EngOilLevel"
#define carinfoOilTempData                                 @"data/carinfoservice/EngOilLevel"
#define carinfoDistTravelledDataAvailable                  @"dataavailable/carinfoservice/OdometerMasterValue"
#define carinfoDistTravelledData                           @"data/carinfoservice/OdometerMasterValue"
#define carinfoFuelP100DataAvailable                       @"dataavailable/carinfoservice/FuelCnptn_D_Actl"
#define carinfoFuelP100Data                                @"data/carinfoservice/FuelCnptn_D_Actl"
#define carinfoAVGFuelP100DataAvailable                    @"dataavailable/carinfoservice/Econometer"
#define carinfoAVGFuelP100Data                             @"data/carinfoservice/Econometer"
#define carinfoInCarTempDataAvailable                      @"dataavailable/carinfoservice/InCarTemp"
#define carinfoInCarTempData                               @"data/carinfoservice/InCarTemp"
#define carinfoDistToEmptyDataAvailable                    @"dataavailable/carinfoservice/DistToEmpty_D_Actl"
#define carinfoDistToEmptyData                             @"data/carinfoservice/DistToEmpty_D_Actl"
#define ihuBrightnessCommandAvailable                      @"commandavailable/ihuSettingsService/displayBrightness"
#define ihuBrightnessCommand                               @"command/ihuSettingsService/displayBrightness"
#define ihuBrightnessDataAvailable                         @"dataavailable/ihuSettingsService/displayBrightness"
#define ihuBrightnessData                                  @"data/ihuSettingsService/displayBrightness"

// Result of a speechRecognitionQuery. Result is encoded in a JSON document. Example: {Result:{"status":0"uuid":"2b558463-467c-4391-bbd1-9a30b903c8a8""utterance""test 12"}}
#define speechRecognitionResultDataAvailable               @"dataavailable/speechRecognitionService/Result"
#define speechRecognitionResultData                        @"data/speechRecognitionService/Result"
// Playload should be a JSON document containing a unique ID conforming to uuid specified in RFC 4122 the spoken language and the listen timeout. Example: {"query": { "language": "en-us" "timeout": "3"  "uuid": "2b558463-467c-4391-bbd1-9a30b903c8a8" } 
#define speechRecognitionQueryCommandAvailable             @"commandavailable/speechRecognitionService/Query"
#define speechRecognitionQueryCommand                      @"command/speechRecognitionService/Query"
// Speech recognition in progress.
#define speechRecognitionBusyDataAvailable                 @"dataavailable/speechRecognitionService/Busy"
#define speechRecognitionBusyData                          @"data/speechRecognitionService/Busy"
//  end a active speech recognition query Playload should be the unique id of the peechRecognitionQuery command
#define speechRecognitionEndQueryCommandAvailable          @"commandavailable/speechRecognitionService/EndQuery"
#define speechRecognitionEndQueryCommand                   @"command/speechRecognitionService/EndQuery"
// Should start to scan for devices
#define keyDetectorStartScanDataAvailable                  @"dataavailable/keyDetectorService/StartScan"
#define keyDetectorStartScanData                           @"data/keyDetectorService/StartScan"
// Should stop to scan for devices
#define keyDetectorStopScanDataAvailable                   @"dataavailable/keyDetectorService/StopScan"
#define keyDetectorStopScanData                            @"data/keyDetectorService/StopScan"
// Payload should be user ID
#define keyDetectorUserFoundCommandAvailable               @"commandavailable/keyDetectorService/UserFound"
#define keyDetectorUserFoundCommand                        @"command/keyDetectorService/UserFound"
#define mediaserviceResourceAvailable                      @"resourceavailable/mediaservice/presence"
#define allmediaserviceData                                @"data/mediaservice/#"
#define allmediaserviceCommand                             @"command/mediaservice/#"
#define climateserviceResourceAvailable                    @"resourceavailable/climateservice/presence"
#define allclimateserviceData                              @"data/climateservice/#"
#define allclimateserviceCommand                           @"command/climateservice/#"
#define navigationserviceResourceAvailable                 @"resourceavailable/navigationservice/presence"
#define allnavigationserviceData                           @"data/navigationservice/#"
#define allnavigationserviceCommand                        @"command/navigationservice/#"
#define dummycarserviceResourceAvailable                   @"resourceavailable/dummycarservice/presence"
#define alldummycarserviceData                             @"data/dummycarservice/#"
#define alldummycarserviceCommand                          @"command/dummycarservice/#"
#define carinfoserviceResourceAvailable                    @"resourceavailable/carinfoservice/presence"
#define allcarinfoserviceData                              @"data/carinfoservice/#"
#define allcarinfoserviceCommand                           @"command/carinfoservice/#"
#define speechRecognitionServiceResourceAvailable          @"resourceavailable/speechRecognitionService/presence"
#define allspeechRecognitionServiceData                    @"data/speechRecognitionService/#"
#define allspeechRecognitionServiceCommand                 @"command/speechRecognitionService/#"
#define keyDetectorServiceResourceAvailable                @"resourceavailable/keyDetectorService/presence"
#define allkeyDetectorServiceData                          @"data/keyDetectorService/#"
#define allkeyDetectorServiceCommand                       @"command/keyDetectorService/#"
#define ihuSettingsServiceResourceAvailable                @"resourceavailable/ihuSettingsService/presence"
#define allihuSettingsServiceData                          @"data/ihuSettingsService/#"
#define ihuSettingsServiceCommand                          @"command/ihuSettingsService/#"
#define allCommandAvailable                                @"commandavailable/#"
#define allDataAvailable                                   @"dataavailable/#"
#define allResourceAvailable                               @"resourceavailable/#"



#endif
